# Generated by Django 4.0.2 on 2022-02-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='Информация про себя')),
                ('photo', models.ImageField(blank=True, upload_to='vizitka/images/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Ваш Email')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='На что ссылка')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
