# Generated by Django 4.0.2 on 2022-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizitka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Ваш Email'),
        ),
        migrations.AddField(
            model_name='links',
            name='extra',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
