# Generated by Django 4.0.2 on 2022-02-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizitka', '0002_links_email_links_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='email',
        ),
    ]
